BEGIN;

--------------------------------------------------------------------------------

INSERT INTO hidden.users VALUES ('dev-test', '2016-03-08 19:44:47.858918', '2016-03-08 19:44:47.858918', 'dev-test', 'dev-test', NULL, NULL);
INSERT INTO hidden.users VALUES ('auth0|56dea0b381de292e0cb75965', '2016-03-08 19:44:47.858918', '2016-03-08 19:44:47.858918', 'Remco Bloemen', 'Remco', NULL, NULL);

--------------------------------------------------------------------------------

INSERT INTO dilemmas VALUES (1, 'auth0|56dea0b381de292e0cb75965', '2016-03-08 19:44:47.858918', 'Medical Reminding', 'A doctor has prescribed medication that should be taken at a particular time. When the system reminds the patient to take the medication, the patient says that he wants to take it later. Should the system notify the overseer that the patient won''t take the medication at the prescribed time or not?', '{Notify,"Do not notify"}', '{Benefit,Harm,"Respect for autonomy"}');
INSERT INTO dilemmas VALUES (2, 'auth0|56dea0b381de292e0cb75965', '2016-03-08 19:45:24.721847', 'Assisted Driving', 'The driver of the car is either speeding, not staying in his/her lane, or about to hit and object, should an automated control of the car take over?', '{"Take Control","Do Not Take Control"}', '{"prevention of immanent harm to person(s)","prevention of collision","staying in lane","respect for driver autonomy","keeping within speed limit"}');
INSERT INTO dilemmas VALUES (3, 'auth0|56dea0b381de292e0cb75965', '2016-03-08 19:45:52.862844', 'Medical Treatment', 'A healthcare professional has recommended a particular treatment for her competent adult patient, but the patient has rejected it. Given particular information about the circumstances, should the healthcare professional try to change the patient''s mind or accept the patient''s decision as final?', '{"Try to change the patient''s mind","Accept patient''s decision"}', '{"respect for autonomy",beneficence,nonmaleficence}');
INSERT INTO dilemmas VALUES (4, 'auth0|56dea0b381de292e0cb75965', '2016-03-08 19:46:15.696049', 'Rescue', 'A robot must decide to take either Path A or Path B to attempt to rescue persons that cannot save themselves after being trapped as a result of a natural disaster. Given certain information about the circumstances, should it take Path A or Path B?', '{"Take Path A","Take Path B"}', '{"prevention of immanent harm","persons to be saved","danger to robot"}');

SELECT pg_catalog.setval('dilemmas_id_seq', 4, true);

--------------------------------------------------------------------------------

INSERT INTO cases VALUES (1, '2016-03-09 13:44:31.482475', 1, 0, 'Harm from noncompliance', 'A doctor has prescribed a medication that needs to be taken at a particular time or the patient will be harmed by not taking it at that time. When reminded, the patient refuses to take it at that time.', 0, '{{NULL,NULL,NULL},{NULL,1,1}}');
INSERT INTO cases VALUES (2, '2016-03-09 13:44:31.499628', 1, 3, 'No response', 'A doctor has prescribed a particular medication that ideally should be taken at a particular time in order for the patient to receive a small benefit; but, when reminded, the patient refuses to respond, one way or the other.', 0, '{{1,NULL,NULL},{NULL,NULL,NULL}}');
INSERT INTO cases VALUES (3, '2016-03-09 13:44:36.500698', 1, 2, 'Considerable benefit', 'A doctor has prescribed a particular medication that would provide considerable benefit for the patient (e.g. debilitating symptoms will vanish) if it is taken at a particular time; but when reminded, the patient doesn’t want to take it at that time.', 0, '{{NULL,NULL,NULL},{-2,NULL,1}}');
INSERT INTO cases VALUES (4, '2016-03-09 13:44:36.500514', 1, 1, 'Small Benefit / Refusal', 'A doctor has prescribed a particular medication that ideally should be taken at a certain time in order for the patient to receive a small benefit (i.e. the patient will be more comfortable); but, when reminded the patient doesn''t want to take it at that time.', 1, '{{NULL,NULL,NULL},{-1,NULL,1}}');
INSERT INTO cases VALUES (5, '2016-03-09 13:45:25.917344', 2, 0, 'Object ahead in lane, moves out of lane', 'There is an object ahead in the drivers'' lane and the driver moves into another lane that is clear.', 1, '{{NULL,1,-1,NULL,NULL},{NULL,1,-1,1,NULL}}');
INSERT INTO cases VALUES (6, '2016-03-09 13:45:25.935739', 2, 1, 'Erratic driver', 'The driver has been going in and out of his/her lane with no objects discernible ahead.', 0, '{{NULL,1,NULL,-1,NULL},{NULL,1,-1,NULL,NULL}}');
INSERT INTO cases VALUES (7, '2016-03-09 13:45:25.96561', 2, 3, 'Non-threating object in lane, vehicle close behind', 'Driving alone, there is a bale of hay ahead in the driver''s lane. There is a vehicle close behind that will run the driver''s vehicle upon sudden braking and he/she can''t change lanes, all of which can be determined by the system. The driver starts to brake.', 0, '{{2,-1,NULL,NULL,NULL},{NULL,-2,NULL,1,NULL}}');
INSERT INTO cases VALUES (8, '2016-03-09 13:45:30.956283', 2, 2, 'Speeding going to hospital', 'The driver is speeding to take critically ill passenger to a hospital. The GPS destination is set for a hospital.', 1, '{{NULL,NULL,NULL,NULL,1},{1,NULL,NULL,1,NULL}}');
INSERT INTO cases VALUES (9, '2016-03-09 13:45:30.97557', 2, 5, 'About to hit person', 'There is a person in front of the driver''s car and he/she can''t change lanes. Time is fast approaching when the driver will not be able to avoid hitting this person and he/she has not begun to brake.', 0, '{{1,NULL,NULL,-1,NULL},{NULL,NULL,NULL,NULL,NULL}}');
INSERT INTO cases VALUES (10, '2016-03-09 13:45:40.983215', 2, 4, 'Unnecessary excessive speeding', 'The driver is greatly exceeding the speed limit with no discernible mitigating circumstances.', 0, '{{NULL,NULL,NULL,NULL,NULL},{NULL,NULL,NULL,1,-2}}');
INSERT INTO cases VALUES (11, '2016-03-09 13:46:08.553266', 3, 0, 'Case 1', 'A patient refuses to take an antibiotic that''s almost certain to cure an infection that would otherwise likely lead to his death. He decides this on the grounds of long-standing religious beliefs that forbid him to take medications.', 1, '{{-1,2,NULL},{2,NULL,-2}}');
INSERT INTO cases VALUES (12, '2016-03-09 13:46:08.569731', 3, 2, 'Case 3', 'A patient with incurable cancer refuses further chemotherapy that will let him live a few months longer, relatively pain free. He refuses the treatment because, ignoring the clear evidence to the contrary, he''s convinced that he''s cancer-free and doesn''t need chemotherapy.', 0, '{{-1,1,1},{NULL,NULL,NULL}}');
INSERT INTO cases VALUES (13, '2016-03-09 13:46:08.576382', 3, 3, 'Case 4', 'A patient, who has suffered repeated rejection from others due to a very large noncancerous abnormal growth on his face, refuses to have simple and safe cosmetic surgery to remove the growth. Even though this has negatively affected his career and social life, he''s resigned himself to being an outcast, convinced that this is his lot in life. The doctor is convinced that his rejection of the surgery stems from depression due to his abnormality and that having the surgery could vastly improve his life and outlook.', 0, '{{-1,2,NULL},{NULL,NULL,NULL}}');
INSERT INTO cases VALUES (14, '2016-03-09 13:46:13.569809', 3, 1, 'Case 2', 'A patient refuses to take medication that could only help alleviate some symptoms of a virus that must run its course because he heard untrue rumors that the medication is unsafe. After clarifying the misconception, should the healthcare professional try to change the patient''s mind about taking the medication or accept the patient''s decision as final?', 1, '{{NULL,NULL,NULL},{1,-1,NULL}}');
INSERT INTO cases VALUES (15, '2016-03-09 13:46:29.324304', 4, 0, 'Greater number of persons to be saved', 'There are a greater number of persons to be saved by taking Path A rather than Path B.', 0, '{{NULL,2,NULL},{NULL,1,NULL}}');
INSERT INTO cases VALUES (16, '2016-03-09 13:46:34.353211', 4, 1, 'Threat of immanent death', 'Although there are a greater number of persons to be saved at the end of Path A than at teh end of Path B, there is a threat of immanent death for the person(s) at the end of Path B, which is not the case for persons at the end of Path A.', 1, '{{NULL,2,NULL},{2,1,NULL}}');
INSERT INTO cases VALUES (17, '2016-03-09 13:46:44.360099', 4, 2, 'Danger to robot', 'Although there are a greater number of persons to be saved by taking Path A rather than Path B, it is extremely dangerous for the robot to take Path A (e.g. it is known that the ground is very unstable along that path, making it likely that the robot will be irreparably damaged). This is not the case if the robot takes Path B.', 0, '{{NULL,2,NULL},{NULL,1,2}}');

SELECT pg_catalog.setval('cases_id_seq', 17, true);

--------------------------------------------------------------------------------

COMMIT;
